### ISSUE TITLE
Very long numbers overflow the swap text input

### ISSUE THREAD

**Issue by danielmkm** [beethovenxfi/beets-frontend#61]
![Screenshot 2022-08-01 at 08 47 36](https://user-images.githubusercontent.com/91405705/182088767-de412aa3-a9b3-4ed9-b5aa-90aa7578574c.png)

**Comment by groninge01** [comment]
@danielmkm 

This looks fixed? I can type any more numbers to get the overflow...

![image](https://user-images.githubusercontent.com/20125808/182768006-567db2e8-f409-4313-a07d-98f280f30cd7.png)

**Comment by groninge01** [comment]
> @danielmkm
> 
> This looks fixed? I can type any more numbers to get the overflow...
> 
> ![image](https://user-images.githubusercontent.com/20125808/182768006-567db2e8-f409-4313-a07d-98f280f30cd7.png)

Ah got the overflow...

![image](https://user-images.githubusercontent.com/20125808/182841177-62e5be7f-5bed-42a9-832e-06ff99398119.png)

**Comment by groninge01** [comment]
@danielmkm Technically it is not an overflow because the input spans the full width and the token selector is overlaid. A quick & dirty work around would be like this:

![image](https://user-images.githubusercontent.com/20125808/183029803-82bb0331-8470-41b1-b32f-fbb2f99cf2c8.png)

I think the final solution would be a redesign of the component where the token selector is not an overlay but next to (or after) the input.
